CREATE TABLE topic (_id INTEGER PRIMARY KEY NOT NULL, subject_id INTEGER NOT NULL REFERENCES subject ON DELETE CASCADE, name TEXT NOT NULL, note TEXT, created_on DEFAULT current_date, seen_on INTEGER);
CREATE TABLE review (_id INTEGER PRIMARY KEY NOT NULL, topic_id INTEGER NOT NULL REFERENCES topic ON DELETE CASCADE, date TEXT, checked INTEGER);
CREATE TABLE review_reminder (review_id INTEGER PRIMARY KEY NOT NULL REFERENCES review ON DELETE CASCADE, date TEXT, topic_id INTEGER NOT NULL);
CREATE TABLE subject (_id INTEGER PRIMARY KEY NOT NULL, name TEXT);
CREATE TRIGGER delete_reminder AFTER UPDATE ON review FOR EACH ROW BEGIN DELETE FROM review_reminder WHERE review_reminder.review_id = old._id